### ISSUE TITLE
Cant find the csv file data set

### ISSUE THREAD

**Issue by ankitwarbhe** [regnna/IPL-Score-Prediction#1]
Can you please add the csv file dataset

**Comment by regnna** [comment]
ya my bad, added the dataset
can you give me some suggestions on how can I push the model(183mb) in github, 
the app is production ready itself , but only the github lfs isn't working for my account, every time I tried it says I Have exceded my monthly quota

**Comment by ankitwarbhe** [comment]
> ya my bad, added the dataset can you give me some suggestions on how can I push the model(183mb) in github, the app is production ready itself , but only the github lfs isn't working for my account, every time I tried it says I Have exceded my monthly quota

Just wait for next month as it says your quota is over or you can get upgraded to github pro 

If you are a student you can get github student pack for free
